//
// Created by ru on 08/25/22.
//

#ifndef NETLONK_DEMO_NL80211_ATTRS_MAP_H
#define NETLONK_DEMO_NL80211_ATTRS_MAP_H
#define ENTRY(x) {x, #x}

struct nl80211_attrs_map {
    unsigned type;
    const char *name;
};

struct nla_policy stats_policy[NL80211_STA_INFO_MAX + 1] = {
        [NL80211_STA_INFO_INACTIVE_TIME] = { .type = NLA_U32 },
        [NL80211_STA_INFO_RX_BYTES] = { .type = NLA_U32 },
        [NL80211_STA_INFO_TX_BYTES] = { .type = NLA_U32 },
        [NL80211_STA_INFO_RX_BYTES64] = { .type = NLA_U64 },
        [NL80211_STA_INFO_TX_BYTES64] = { .type = NLA_U64 },
        [NL80211_STA_INFO_RX_PACKETS] = { .type = NLA_U32 },
        [NL80211_STA_INFO_TX_PACKETS] = { .type = NLA_U32 },
        [NL80211_STA_INFO_BEACON_RX] = { .type = NLA_U64},
        [NL80211_STA_INFO_SIGNAL] = { .type = NLA_U8 },
        [NL80211_STA_INFO_T_OFFSET] = { .type = NLA_U64 },
        [NL80211_STA_INFO_TX_BITRATE] = { .type = NLA_NESTED },
        [NL80211_STA_INFO_RX_BITRATE] = { .type = NLA_NESTED },
        [NL80211_STA_INFO_LLID] = { .type = NLA_U16 },
        [NL80211_STA_INFO_PLID] = { .type = NLA_U16 },
        [NL80211_STA_INFO_PLINK_STATE] = { .type = NLA_U8 },
        [NL80211_STA_INFO_TX_RETRIES] = { .type = NLA_U32 },
        [NL80211_STA_INFO_TX_FAILED] = { .type = NLA_U32 },
        [NL80211_STA_INFO_BEACON_LOSS] = { .type = NLA_U32},
        [NL80211_STA_INFO_RX_DROP_MISC] = { .type = NLA_U64},
        [NL80211_STA_INFO_STA_FLAGS] =
                { .minlen = sizeof(struct nl80211_sta_flag_update) },
        [NL80211_STA_INFO_LOCAL_PM] = { .type = NLA_U32},
        [NL80211_STA_INFO_PEER_PM] = { .type = NLA_U32},
        [NL80211_STA_INFO_NONPEER_PM] = { .type = NLA_U32},
        [NL80211_STA_INFO_CHAIN_SIGNAL] = { .type = NLA_NESTED },
        [NL80211_STA_INFO_CHAIN_SIGNAL_AVG] = { .type = NLA_NESTED },
        [NL80211_STA_INFO_TID_STATS] = { .type = NLA_NESTED },
        [NL80211_STA_INFO_BSS_PARAM] = { .type = NLA_NESTED },
        [NL80211_STA_INFO_RX_DURATION] = { .type = NLA_U64 },
        [NL80211_STA_INFO_TX_DURATION] = { .type = NLA_U64 },
        [NL80211_STA_INFO_ACK_SIGNAL] = {.type = NLA_U8 },
        [NL80211_STA_INFO_ACK_SIGNAL_AVG] = { .type = NLA_U8 },
        [NL80211_STA_INFO_AIRTIME_LINK_METRIC] = { .type = NLA_U32 },
        [NL80211_STA_INFO_CONNECTED_TO_AS] = { .type = NLA_U8 },
        [NL80211_STA_INFO_CONNECTED_TO_GATE] = { .type = NLA_U8 },
};


struct nl80211_attrs_map nl_attr_map [] =
        {
                ENTRY(NL80211_ATTR_UNSPEC),

                ENTRY(NL80211_ATTR_WIPHY),
                ENTRY(NL80211_ATTR_WIPHY_NAME),

                ENTRY(NL80211_ATTR_IFINDEX),
                ENTRY(NL80211_ATTR_IFNAME),
                ENTRY(NL80211_ATTR_IFTYPE),

                ENTRY(NL80211_ATTR_MAC),

                ENTRY(NL80211_ATTR_KEY_DATA),
                ENTRY(NL80211_ATTR_KEY_IDX),
                ENTRY(NL80211_ATTR_KEY_CIPHER),
                ENTRY(NL80211_ATTR_KEY_SEQ),
                ENTRY(NL80211_ATTR_KEY_DEFAULT),

                ENTRY(NL80211_ATTR_BEACON_INTERVAL),
                ENTRY(NL80211_ATTR_DTIM_PERIOD),
                ENTRY(NL80211_ATTR_BEACON_HEAD),
                ENTRY(NL80211_ATTR_BEACON_TAIL),

                ENTRY(NL80211_ATTR_STA_AID),
                ENTRY(NL80211_ATTR_STA_FLAGS),
                ENTRY(NL80211_ATTR_STA_LISTEN_INTERVAL),
                ENTRY(NL80211_ATTR_STA_SUPPORTED_RATES),
                ENTRY(NL80211_ATTR_STA_VLAN),
                ENTRY(NL80211_ATTR_STA_INFO),

                ENTRY(NL80211_ATTR_WIPHY_BANDS),

                ENTRY(NL80211_ATTR_MNTR_FLAGS),

                ENTRY(NL80211_ATTR_MESH_ID),
                ENTRY(NL80211_ATTR_STA_PLINK_ACTION),
                ENTRY(NL80211_ATTR_MPATH_NEXT_HOP),
                ENTRY(NL80211_ATTR_MPATH_INFO),

                ENTRY(NL80211_ATTR_BSS_CTS_PROT),
                ENTRY(NL80211_ATTR_BSS_SHORT_PREAMBLE),
                ENTRY(NL80211_ATTR_BSS_SHORT_SLOT_TIME),

                ENTRY(NL80211_ATTR_HT_CAPABILITY),

                ENTRY(NL80211_ATTR_SUPPORTED_IFTYPES),

                ENTRY(NL80211_ATTR_REG_ALPHA2),
                ENTRY(NL80211_ATTR_REG_RULES),

                ENTRY(NL80211_ATTR_MESH_CONFIG),

                ENTRY(NL80211_ATTR_BSS_BASIC_RATES),

                ENTRY(NL80211_ATTR_WIPHY_TXQ_PARAMS),
                ENTRY(NL80211_ATTR_WIPHY_FREQ),
                ENTRY(NL80211_ATTR_WIPHY_CHANNEL_TYPE),

                ENTRY(NL80211_ATTR_KEY_DEFAULT_MGMT),

                ENTRY(NL80211_ATTR_MGMT_SUBTYPE),
                ENTRY(NL80211_ATTR_IE),

                ENTRY(NL80211_ATTR_MAX_NUM_SCAN_SSIDS),

                ENTRY(NL80211_ATTR_SCAN_FREQUENCIES),
                ENTRY(NL80211_ATTR_SCAN_SSIDS),
                /* replaces old SCAN_GENERATION */
                ENTRY(NL80211_ATTR_GENERATION),
                ENTRY(NL80211_ATTR_BSS),

                ENTRY(NL80211_ATTR_REG_INITIATOR),
                ENTRY(NL80211_ATTR_REG_TYPE),

                ENTRY(NL80211_ATTR_SUPPORTED_COMMANDS),

                ENTRY(NL80211_ATTR_FRAME),
                ENTRY(NL80211_ATTR_SSID),
                ENTRY(NL80211_ATTR_AUTH_TYPE),
                ENTRY(NL80211_ATTR_REASON_CODE),

                ENTRY(NL80211_ATTR_KEY_TYPE),

                ENTRY(NL80211_ATTR_MAX_SCAN_IE_LEN),
                ENTRY(NL80211_ATTR_CIPHER_SUITES),

                ENTRY(NL80211_ATTR_FREQ_BEFORE),
                ENTRY(NL80211_ATTR_FREQ_AFTER),

                ENTRY(NL80211_ATTR_FREQ_FIXED),


                ENTRY(NL80211_ATTR_WIPHY_RETRY_SHORT),
                ENTRY(NL80211_ATTR_WIPHY_RETRY_LONG),
                ENTRY(NL80211_ATTR_WIPHY_FRAG_THRESHOLD),
                ENTRY(NL80211_ATTR_WIPHY_RTS_THRESHOLD),

                ENTRY(NL80211_ATTR_TIMED_OUT),

                ENTRY(NL80211_ATTR_USE_MFP),

                ENTRY(NL80211_ATTR_STA_FLAGS2),

                ENTRY(NL80211_ATTR_CONTROL_PORT),

                ENTRY(NL80211_ATTR_TESTDATA),

                ENTRY(NL80211_ATTR_PRIVACY),

                ENTRY(NL80211_ATTR_DISCONNECTED_BY_AP),
                ENTRY(NL80211_ATTR_STATUS_CODE),

                ENTRY(NL80211_ATTR_CIPHER_SUITES_PAIRWISE),
                ENTRY(NL80211_ATTR_CIPHER_SUITE_GROUP),
                ENTRY(NL80211_ATTR_WPA_VERSIONS),
                ENTRY(NL80211_ATTR_AKM_SUITES),

                ENTRY(NL80211_ATTR_REQ_IE),
                ENTRY(NL80211_ATTR_RESP_IE),

                ENTRY(NL80211_ATTR_PREV_BSSID),

                ENTRY(NL80211_ATTR_KEY),
                ENTRY(NL80211_ATTR_KEYS),

                ENTRY(NL80211_ATTR_PID),

                ENTRY(NL80211_ATTR_4ADDR),

                ENTRY(NL80211_ATTR_SURVEY_INFO),

                ENTRY(NL80211_ATTR_PMKID),
                ENTRY(NL80211_ATTR_MAX_NUM_PMKIDS),

                ENTRY(NL80211_ATTR_DURATION),

                ENTRY(NL80211_ATTR_COOKIE),

                ENTRY(NL80211_ATTR_WIPHY_COVERAGE_CLASS),

                ENTRY(NL80211_ATTR_TX_RATES),

                ENTRY(NL80211_ATTR_FRAME_MATCH),

                ENTRY(NL80211_ATTR_ACK),

                ENTRY(NL80211_ATTR_PS_STATE),

                ENTRY(NL80211_ATTR_CQM),

                ENTRY(NL80211_ATTR_LOCAL_STATE_CHANGE),

                ENTRY(NL80211_ATTR_AP_ISOLATE),

                ENTRY(NL80211_ATTR_WIPHY_TX_POWER_SETTING),
                ENTRY(NL80211_ATTR_WIPHY_TX_POWER_LEVEL),

                ENTRY(NL80211_ATTR_TX_FRAME_TYPES),
                ENTRY(NL80211_ATTR_RX_FRAME_TYPES),
                ENTRY(NL80211_ATTR_FRAME_TYPE),

                ENTRY(NL80211_ATTR_CONTROL_PORT_ETHERTYPE),
                ENTRY(NL80211_ATTR_CONTROL_PORT_NO_ENCRYPT),

                ENTRY(NL80211_ATTR_SUPPORT_IBSS_RSN),

                ENTRY(NL80211_ATTR_WIPHY_ANTENNA_TX),
                ENTRY(NL80211_ATTR_WIPHY_ANTENNA_RX),

                ENTRY(NL80211_ATTR_MCAST_RATE),

                ENTRY(NL80211_ATTR_OFFCHANNEL_TX_OK),

                ENTRY(NL80211_ATTR_BSS_HT_OPMODE),

                ENTRY(NL80211_ATTR_KEY_DEFAULT_TYPES),

                ENTRY(NL80211_ATTR_MAX_REMAIN_ON_CHANNEL_DURATION),

                ENTRY(NL80211_ATTR_MESH_SETUP),

                ENTRY(NL80211_ATTR_WIPHY_ANTENNA_AVAIL_TX),
                ENTRY(NL80211_ATTR_WIPHY_ANTENNA_AVAIL_RX),

                ENTRY(NL80211_ATTR_SUPPORT_MESH_AUTH),
                ENTRY(NL80211_ATTR_STA_PLINK_STATE),

                ENTRY(NL80211_ATTR_WOWLAN_TRIGGERS),
                ENTRY(NL80211_ATTR_WOWLAN_TRIGGERS_SUPPORTED),

                ENTRY(NL80211_ATTR_SCHED_SCAN_INTERVAL),

                ENTRY(NL80211_ATTR_INTERFACE_COMBINATIONS),
                ENTRY(NL80211_ATTR_SOFTWARE_IFTYPES),

                ENTRY(NL80211_ATTR_REKEY_DATA),

                ENTRY(NL80211_ATTR_MAX_NUM_SCHED_SCAN_SSIDS),
                ENTRY(NL80211_ATTR_MAX_SCHED_SCAN_IE_LEN),

                ENTRY(NL80211_ATTR_SCAN_SUPP_RATES),

                ENTRY(NL80211_ATTR_HIDDEN_SSID),

                ENTRY(NL80211_ATTR_IE_PROBE_RESP),
                ENTRY(NL80211_ATTR_IE_ASSOC_RESP),

                ENTRY(NL80211_ATTR_STA_WME),
                ENTRY(NL80211_ATTR_SUPPORT_AP_UAPSD),

                ENTRY(NL80211_ATTR_ROAM_SUPPORT),

                ENTRY(NL80211_ATTR_SCHED_SCAN_MATCH),
                ENTRY(NL80211_ATTR_MAX_MATCH_SETS),

                ENTRY(NL80211_ATTR_PMKSA_CANDIDATE),

                ENTRY(NL80211_ATTR_TX_NO_CCK_RATE),

                ENTRY(NL80211_ATTR_TDLS_ACTION),
                ENTRY(NL80211_ATTR_TDLS_DIALOG_TOKEN),
                ENTRY(NL80211_ATTR_TDLS_OPERATION),
                ENTRY(NL80211_ATTR_TDLS_SUPPORT),
                ENTRY(NL80211_ATTR_TDLS_EXTERNAL_SETUP),

                ENTRY(NL80211_ATTR_DEVICE_AP_SME),

                ENTRY(NL80211_ATTR_DONT_WAIT_FOR_ACK),

                ENTRY(NL80211_ATTR_FEATURE_FLAGS),

                ENTRY(NL80211_ATTR_PROBE_RESP_OFFLOAD),

                ENTRY(NL80211_ATTR_PROBE_RESP),

                ENTRY(NL80211_ATTR_DFS_REGION),

                ENTRY(NL80211_ATTR_DISABLE_HT),
                ENTRY(NL80211_ATTR_HT_CAPABILITY_MASK),

                ENTRY(NL80211_ATTR_NOACK_MAP),

                ENTRY(NL80211_ATTR_INACTIVITY_TIMEOUT),

                ENTRY(NL80211_ATTR_RX_SIGNAL_DBM),

                ENTRY(NL80211_ATTR_BG_SCAN_PERIOD),

                ENTRY(NL80211_ATTR_WDEV),

                ENTRY(NL80211_ATTR_USER_REG_HINT_TYPE),

                ENTRY(NL80211_ATTR_CONN_FAILED_REASON),

                ENTRY(NL80211_ATTR_AUTH_DATA),

                ENTRY(NL80211_ATTR_VHT_CAPABILITY),

                ENTRY(NL80211_ATTR_SCAN_FLAGS),

                ENTRY(NL80211_ATTR_CHANNEL_WIDTH),
                ENTRY(NL80211_ATTR_CENTER_FREQ1),
                ENTRY(NL80211_ATTR_CENTER_FREQ2),

                ENTRY(NL80211_ATTR_P2P_CTWINDOW),
                ENTRY(NL80211_ATTR_P2P_OPPPS),

                ENTRY(NL80211_ATTR_LOCAL_MESH_POWER_MODE),

                ENTRY(NL80211_ATTR_ACL_POLICY),

                ENTRY(NL80211_ATTR_MAC_ADDRS),

                ENTRY(NL80211_ATTR_MAC_ACL_MAX),

                ENTRY(NL80211_ATTR_RADAR_EVENT),

                ENTRY(NL80211_ATTR_EXT_CAPA),
                ENTRY(NL80211_ATTR_EXT_CAPA_MASK),

                ENTRY(NL80211_ATTR_STA_CAPABILITY),
                ENTRY(NL80211_ATTR_STA_EXT_CAPABILITY),

                ENTRY(NL80211_ATTR_PROTOCOL_FEATURES),
                ENTRY(NL80211_ATTR_SPLIT_WIPHY_DUMP),

                ENTRY(NL80211_ATTR_DISABLE_VHT),
                ENTRY(NL80211_ATTR_VHT_CAPABILITY_MASK),

                ENTRY(NL80211_ATTR_MDID),
                ENTRY(NL80211_ATTR_IE_RIC),

                ENTRY(NL80211_ATTR_CRIT_PROT_ID),
                ENTRY(NL80211_ATTR_MAX_CRIT_PROT_DURATION),

                ENTRY(NL80211_ATTR_PEER_AID),

                ENTRY(NL80211_ATTR_COALESCE_RULE),

                ENTRY(NL80211_ATTR_CH_SWITCH_COUNT),
                ENTRY(NL80211_ATTR_CH_SWITCH_BLOCK_TX),
                ENTRY(NL80211_ATTR_CSA_IES),
                ENTRY(NL80211_ATTR_CNTDWN_OFFS_BEACON),
                ENTRY(NL80211_ATTR_CNTDWN_OFFS_PRESP),

                ENTRY(NL80211_ATTR_RXMGMT_FLAGS),

                ENTRY(NL80211_ATTR_STA_SUPPORTED_CHANNELS),

                ENTRY(NL80211_ATTR_STA_SUPPORTED_OPER_CLASSES),

                ENTRY(NL80211_ATTR_HANDLE_DFS),

                ENTRY(NL80211_ATTR_SUPPORT_5_MHZ),
                ENTRY(NL80211_ATTR_SUPPORT_10_MHZ),

                ENTRY(NL80211_ATTR_OPMODE_NOTIF),

                ENTRY(NL80211_ATTR_VENDOR_ID),
                ENTRY(NL80211_ATTR_VENDOR_SUBCMD),
                ENTRY(NL80211_ATTR_VENDOR_DATA),
                ENTRY(NL80211_ATTR_VENDOR_EVENTS),

                ENTRY(NL80211_ATTR_QOS_MAP),

                ENTRY(NL80211_ATTR_MAC_HINT),
                ENTRY(NL80211_ATTR_WIPHY_FREQ_HINT),

                ENTRY(NL80211_ATTR_MAX_AP_ASSOC_STA),

                ENTRY(NL80211_ATTR_TDLS_PEER_CAPABILITY),

                ENTRY(NL80211_ATTR_SOCKET_OWNER),

                ENTRY(NL80211_ATTR_CSA_C_OFFSETS_TX),
                ENTRY(NL80211_ATTR_MAX_CSA_COUNTERS),

                ENTRY(NL80211_ATTR_TDLS_INITIATOR),

                ENTRY(NL80211_ATTR_USE_RRM),

                ENTRY(NL80211_ATTR_WIPHY_DYN_ACK),

                ENTRY(NL80211_ATTR_TSID),
                ENTRY(NL80211_ATTR_USER_PRIO),
                ENTRY(NL80211_ATTR_ADMITTED_TIME),

                ENTRY(NL80211_ATTR_SMPS_MODE),

                ENTRY(NL80211_ATTR_OPER_CLASS),

                ENTRY(NL80211_ATTR_MAC_MASK),

                ENTRY(NL80211_ATTR_WIPHY_SELF_MANAGED_REG),

                ENTRY(NL80211_ATTR_EXT_FEATURES),

                ENTRY(NL80211_ATTR_SURVEY_RADIO_STATS),

                ENTRY(NL80211_ATTR_NETNS_FD),

                ENTRY(NL80211_ATTR_SCHED_SCAN_DELAY),

                ENTRY(NL80211_ATTR_REG_INDOOR),

                ENTRY(NL80211_ATTR_MAX_NUM_SCHED_SCAN_PLANS),
                ENTRY(NL80211_ATTR_MAX_SCAN_PLAN_INTERVAL),
                ENTRY(NL80211_ATTR_MAX_SCAN_PLAN_ITERATIONS),
                ENTRY(NL80211_ATTR_SCHED_SCAN_PLANS),

                ENTRY(NL80211_ATTR_PBSS),

                ENTRY(NL80211_ATTR_BSS_SELECT),

                ENTRY(NL80211_ATTR_STA_SUPPORT_P2P_PS),

                ENTRY(NL80211_ATTR_PAD),

                ENTRY(NL80211_ATTR_IFTYPE_EXT_CAPA),

                ENTRY(NL80211_ATTR_MU_MIMO_GROUP_DATA),
                ENTRY(NL80211_ATTR_MU_MIMO_FOLLOW_MAC_ADDR),

                ENTRY(NL80211_ATTR_SCAN_START_TIME_TSF),
                ENTRY(NL80211_ATTR_SCAN_START_TIME_TSF_BSSID),
                ENTRY(NL80211_ATTR_MEASUREMENT_DURATION),
                ENTRY(NL80211_ATTR_MEASUREMENT_DURATION_MANDATORY),

                ENTRY(NL80211_ATTR_MESH_PEER_AID),

                ENTRY(NL80211_ATTR_NAN_MASTER_PREF),
                ENTRY(NL80211_ATTR_BANDS),
                ENTRY(NL80211_ATTR_NAN_FUNC),
                ENTRY(NL80211_ATTR_NAN_MATCH),

                ENTRY(NL80211_ATTR_FILS_KEK),
                ENTRY(NL80211_ATTR_FILS_NONCES),

                ENTRY(NL80211_ATTR_MULTICAST_TO_UNICAST_ENABLED),

                ENTRY(NL80211_ATTR_BSSID),

                ENTRY(NL80211_ATTR_SCHED_SCAN_RELATIVE_RSSI),
                ENTRY(NL80211_ATTR_SCHED_SCAN_RSSI_ADJUST),

                ENTRY(NL80211_ATTR_TIMEOUT_REASON),

                ENTRY(NL80211_ATTR_FILS_ERP_USERNAME),
                ENTRY(NL80211_ATTR_FILS_ERP_REALM),
                ENTRY(NL80211_ATTR_FILS_ERP_NEXT_SEQ_NUM),
                ENTRY(NL80211_ATTR_FILS_ERP_RRK),
                ENTRY(NL80211_ATTR_FILS_CACHE_ID),

                ENTRY(NL80211_ATTR_PMK),

                ENTRY(NL80211_ATTR_SCHED_SCAN_MULTI),
                ENTRY(NL80211_ATTR_SCHED_SCAN_MAX_REQS),

                ENTRY(NL80211_ATTR_WANT_1X_4WAY_HS),
                ENTRY(NL80211_ATTR_PMKR0_NAME),
                ENTRY(NL80211_ATTR_PORT_AUTHORIZED),

                ENTRY(NL80211_ATTR_EXTERNAL_AUTH_ACTION),
                ENTRY(NL80211_ATTR_EXTERNAL_AUTH_SUPPORT),

                ENTRY(NL80211_ATTR_NSS),
                ENTRY(NL80211_ATTR_ACK_SIGNAL),

                ENTRY(NL80211_ATTR_CONTROL_PORT_OVER_NL80211),

                ENTRY(NL80211_ATTR_TXQ_STATS),
                ENTRY(NL80211_ATTR_TXQ_LIMIT),
                ENTRY(NL80211_ATTR_TXQ_MEMORY_LIMIT),
                ENTRY(NL80211_ATTR_TXQ_QUANTUM),

                ENTRY(NL80211_ATTR_HE_CAPABILITY),

                ENTRY(NL80211_ATTR_FTM_RESPONDER),

                ENTRY(NL80211_ATTR_FTM_RESPONDER_STATS),

                ENTRY(NL80211_ATTR_TIMEOUT),

                ENTRY(NL80211_ATTR_PEER_MEASUREMENTS),

                ENTRY(NL80211_ATTR_AIRTIME_WEIGHT),
                ENTRY(NL80211_ATTR_STA_TX_POWER_SETTING),
                ENTRY(NL80211_ATTR_STA_TX_POWER),

                ENTRY(NL80211_ATTR_SAE_PASSWORD),

                ENTRY(NL80211_ATTR_TWT_RESPONDER),

                ENTRY(NL80211_ATTR_HE_OBSS_PD),

                ENTRY(NL80211_ATTR_WIPHY_EDMG_CHANNELS),
                ENTRY(NL80211_ATTR_WIPHY_EDMG_BW_CONFIG),

                ENTRY(NL80211_ATTR_VLAN_ID),

                ENTRY(NL80211_ATTR_HE_BSS_COLOR),

                ENTRY(NL80211_ATTR_IFTYPE_AKM_SUITES),

                ENTRY(NL80211_ATTR_TID_CONFIG),

                ENTRY(NL80211_ATTR_CONTROL_PORT_NO_PREAUTH),

                ENTRY(NL80211_ATTR_PMK_LIFETIME),
                ENTRY(NL80211_ATTR_PMK_REAUTH_THRESHOLD),

                ENTRY(NL80211_ATTR_RECEIVE_MULTICAST),
                ENTRY(NL80211_ATTR_WIPHY_FREQ_OFFSET),
                ENTRY(NL80211_ATTR_CENTER_FREQ1_OFFSET),
                ENTRY(NL80211_ATTR_SCAN_FREQ_KHZ),

                ENTRY(NL80211_ATTR_HE_6GHZ_CAPABILITY),

                ENTRY(NL80211_ATTR_FILS_DISCOVERY),

                ENTRY(NL80211_ATTR_UNSOL_BCAST_PROBE_RESP),

                ENTRY(NL80211_ATTR_S1G_CAPABILITY),
                ENTRY(NL80211_ATTR_S1G_CAPABILITY_MASK),

                ENTRY(NL80211_ATTR_SAE_PWE),

                ENTRY(NL80211_ATTR_RECONNECT_REQUESTED),

                ENTRY(NL80211_ATTR_SAR_SPEC),

                ENTRY(NL80211_ATTR_DISABLE_HE),

                ENTRY(NL80211_ATTR_OBSS_COLOR_BITMAP),

                ENTRY(NL80211_ATTR_COLOR_CHANGE_COUNT),
                ENTRY(NL80211_ATTR_COLOR_CHANGE_COLOR),
                ENTRY(NL80211_ATTR_COLOR_CHANGE_ELEMS),

                ENTRY(NL80211_ATTR_MBSSID_CONFIG),
                ENTRY(NL80211_ATTR_MBSSID_ELEMS),

                ENTRY(NL80211_ATTR_RADAR_BACKGROUND),

                ENTRY(NL80211_ATTR_AP_SETTINGS_FLAGS),

                ENTRY(NL80211_ATTR_EHT_CAPABILITY)

        };
#endif //NETLONK_DEMO_NL80211_ATTRS_MAP_H
